# Generated by Django 4.1.6 on 2023-02-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='profile_image',
        ),
    ]
