# Generated by Django 4.1.6 on 2023-02-14 18:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
