# Generated by Django 4.1.6 on 2023-02-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_category_profile_image_alter_post_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='profile_image',
            new_name='category_image',
        ),
    ]
