# Generated by Django 4.1.6 on 2023-02-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_profile_image_category_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_image',
            new_name='profile_image',
        ),
    ]
