# Generated by Django 4.1.6 on 2023-02-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='post/sta-je-html.jpg', upload_to='post/'),
        ),
    ]
